/**
 * ProjectFlow Database Types
 * 
 * This file provides type definitions for the database schema.
 * Types are auto-generated from the Supabase database schema using:
 *   pnpm db:generate-types
 * 
 * Manual type aliases are provided for backward compatibility.
 * 
 * NOTE: Run `pnpm db:generate-types` first to generate types-generated.ts
 */

// Import generated types from Supabase CLI
// This file is generated by running: pnpm db:generate-types
// @ts-expect-error - File may not exist until types are generated. Run `pnpm db:generate-types` first.
import type { Database as GeneratedDatabase } from './types-generated';

/**
 * Database schema type mapping for Supabase
 * This is the main type used by Supabase clients
 * 
 * Run `pnpm db:generate-types` to generate actual types from your database schema.
 */
export type Database = GeneratedDatabase;

/**
 * Represents a project in the system
 * Type alias for backward compatibility
 */
export type Project = GeneratedDatabase['public']['Tables']['projects']['Row'];

/**
 * Represents a task within a project
 * Type alias for backward compatibility
 */
export type Task = GeneratedDatabase['public']['Tables']['tasks']['Row'];

/**
 * Represents a session snapshot for agent state management
 * Type alias for backward compatibility
 */
export type AgentSession = GeneratedDatabase['public']['Tables']['agent_sessions']['Row'];

/**
 * Represents the shape of data when inserting a new project
 */
export type ProjectInsert = Omit<
  GeneratedDatabase['public']['Tables']['projects']['Insert'],
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a project
 */
export type ProjectUpdate = GeneratedDatabase['public']['Tables']['projects']['Update'];

/**
 * Represents the shape of data when inserting a new task
 */
export type TaskInsert = Omit<
  GeneratedDatabase['public']['Tables']['tasks']['Insert'],
  'id' | 'project_id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a task
 */
export type TaskUpdate = GeneratedDatabase['public']['Tables']['tasks']['Update'];

/**
 * Represents the shape of data when inserting a new agent session
 */
export type AgentSessionInsert = Omit<
  GeneratedDatabase['public']['Tables']['agent_sessions']['Insert'],
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating an agent session
 */
export type AgentSessionUpdate = GeneratedDatabase['public']['Tables']['agent_sessions']['Update'];
