/**
 * ProjectFlow Database Types
 * 
 * This file provides type definitions for the database schema.
 * Types are auto-generated from the Supabase database schema using:
 *   pnpm db:generate-types
 * 
 * Manual type aliases are provided for backward compatibility.
 * 
 * NOTE: Run `pnpm db:generate-types` first to generate types-generated.ts
 */

// Import generated types from Supabase CLI
// This file is generated by running: pnpm db:generate-types
import type { Database as GeneratedDatabase } from './types-generated';

/**
 * Database schema type mapping for Supabase
 * This is the main type used by Supabase clients
 * 
 * Run `pnpm db:generate-types` to generate actual types from your database schema.
 */
export type Database = GeneratedDatabase;

/**
 * Represents a project in the system
 * Type alias for backward compatibility
 */
export type Project = GeneratedDatabase['public']['Tables']['projects']['Row'];

/**
 * Represents a task within a project
 * Type alias for backward compatibility
 */
export type Task = GeneratedDatabase['public']['Tables']['tasks']['Row'];

/**
 * Represents a session snapshot for agent state management
 * Type alias for backward compatibility
 */
export type AgentSession = GeneratedDatabase['public']['Tables']['agent_sessions']['Row'];

/**
 * Represents an event in the event log (source of truth)
 * Type alias for backward compatibility
 */
export type Event = GeneratedDatabase['public']['Tables']['events']['Row'];

/**
 * Represents an artifact produced during task work
 * Type alias for backward compatibility
 */
export type Artifact = GeneratedDatabase['public']['Tables']['artifacts']['Row'];

/**
 * Represents a checkpoint (resumable project snapshot)
 * Type alias for backward compatibility
 */
export type Checkpoint = GeneratedDatabase['public']['Tables']['checkpoints']['Row'];

/**
 * Represents a decision record
 * Type alias for backward compatibility
 */
export type Decision = GeneratedDatabase['public']['Tables']['decisions']['Row'];

/**
 * Represents a pending OAuth authorization request
 * Type alias for backward compatibility
 */
export type OAuthPendingRequest = GeneratedDatabase['public']['Tables']['oauth_pending_requests']['Row'];

/**
 * Represents an outcome record for tracking decision/task results
 * Type alias for backward compatibility
 */
export type Outcome = GeneratedDatabase['public']['Tables']['outcomes']['Row'];

/**
 * Represents a constraint (enforceable rule)
 * Type alias for backward compatibility
 */
export type Constraint = GeneratedDatabase['public']['Tables']['constraints']['Row'];

/**
 * Represents a project specification (goals, deliverables, risks)
 * Type alias for backward compatibility
 */
export type ProjectSpec = {
  id: string;
  project_id: string;
  goals: string;
  definition_of_done: string;
  deliverables: any; // JSONB
  repo_context: any; // JSONB
  risk_areas: string[];
  preferences: any; // JSONB
  gate_pack_id: string | null;
  custom_gates: any; // JSONB
  created_at: string;
  updated_at: string;
  user_id: string;
};

/**
 * Represents the shape of data when inserting a new project
 */
export type ProjectInsert = Omit<
  GeneratedDatabase['public']['Tables']['projects']['Insert'],
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a project
 */
export type ProjectUpdate = GeneratedDatabase['public']['Tables']['projects']['Update'];

/**
 * Represents the shape of data when inserting a new task
 */
export type TaskInsert = Omit<
  GeneratedDatabase['public']['Tables']['tasks']['Insert'],
  'id' | 'project_id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a task
 */
export type TaskUpdate = GeneratedDatabase['public']['Tables']['tasks']['Update'];

/**
 * Represents the shape of data when inserting a new agent session
 */
export type AgentSessionInsert = Omit<
  GeneratedDatabase['public']['Tables']['agent_sessions']['Insert'],
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating an agent session
 */
export type AgentSessionUpdate = GeneratedDatabase['public']['Tables']['agent_sessions']['Update'];

/**
 * Represents the shape of data when inserting a new event
 */
export type EventInsert = Omit<
  GeneratedDatabase['public']['Tables']['events']['Insert'],
  'id' | 'created_at'
>;

/**
 * Represents the shape of data when inserting a new artifact
 */
export type ArtifactInsert = Omit<
  GeneratedDatabase['public']['Tables']['artifacts']['Insert'],
  'id' | 'user_id' | 'created_at'
>;

/**
 * Represents the shape of data when updating an artifact
 */
export type ArtifactUpdate = GeneratedDatabase['public']['Tables']['artifacts']['Update'];

/**
 * Represents the shape of data when inserting a new checkpoint
 */
export type CheckpointInsert = Omit<
  GeneratedDatabase['public']['Tables']['checkpoints']['Insert'],
  'id' | 'user_id' | 'created_at'
>;

/**
 * Represents the shape of data when updating a checkpoint
 */
export type CheckpointUpdate = GeneratedDatabase['public']['Tables']['checkpoints']['Update'];

/**
 * Represents the shape of data when inserting a new decision
 */
export type DecisionInsert = Omit<
  GeneratedDatabase['public']['Tables']['decisions']['Insert'],
  'id' | 'user_id' | 'created_at'
>;

/**
 * Represents the shape of data when updating a decision
 */
export type DecisionUpdate = GeneratedDatabase['public']['Tables']['decisions']['Update'];

/**
 * Represents the shape of data when inserting a new OAuth pending request
 */
export type OAuthPendingRequestInsert = Omit<
  GeneratedDatabase['public']['Tables']['oauth_pending_requests']['Insert'],
  'id' | 'created_at'
>;

/**
 * Represents the shape of data when updating an OAuth pending request
 */
export type OAuthPendingRequestUpdate = GeneratedDatabase['public']['Tables']['oauth_pending_requests']['Update'];

/**
 * Represents the shape of data when inserting a new outcome
 */
export type OutcomeInsert = Omit<
  GeneratedDatabase['public']['Tables']['outcomes']['Insert'],
  'id' | 'user_id' | 'created_at'
>;

/**
 * Represents the shape of data when updating an outcome
 */
export type OutcomeUpdate = GeneratedDatabase['public']['Tables']['outcomes']['Update'];

/**
 * Represents the shape of data when inserting a new constraint
 */
export type ConstraintInsert = Omit<
  GeneratedDatabase['public']['Tables']['constraints']['Insert'],
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a constraint
 */
export type ConstraintUpdate = GeneratedDatabase['public']['Tables']['constraints']['Update'];

/**
 * Represents the shape of data when inserting a new project spec
 */
export type ProjectSpecInsert = Omit<
  ProjectSpec,
  'id' | 'user_id' | 'created_at' | 'updated_at'
>;

/**
 * Represents the shape of data when updating a project spec
 */
export type ProjectSpecUpdate = Partial<ProjectSpecInsert>;
